# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
  - repository: test
    type: github
    name: ebogatenkov/test
    ref: refs/heads/main
    endpoint: githubPAT
  - repository: test2
    type: github
    name: ebogatenkov/test2
    ref: refs/heads/main
    endpoint: githubPAT

trigger:
  none
pr:
  none

stages:
  - stage: buildDevelopment
    displayName: "build | development"
    jobs:
    - job: myjob
      displayName: "build development version"
      timeoutInMinutes: 60 # 1 hour
      pool:
        Azure Pipelines
      steps:
      - checkout: none
      - script: echo "hello code"
